### PR TITLE
Close db connections after all usages

### PR DESCRIPTION
**Pull request by cauebs**
This is necessary to avoid relying on the garbage collector to close file descriptors.

### CODE REVIEW

**Comment by JPTIZ** [comment]
We can use with a context-manager as well: https://dataset.readthedocs.io/en/latest/quickstart.html?highlight=context#using-transactions

**Review by abarichello — APPROVED** [review]
`review.close()` xD

**Comment by cauebs** [comment]
@JPTIZ Well, that's for transactions. I could check if every time we open the database all we do can be bunched into a single transaction, but I'd rather make my own context manager. This shouldn't take long.

**Review by JPTIZ — APPROVED** [review]
```python
    with open_review(self) as review:
        review.accept()
```

xD

**Pull request merged**
